apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-argo-application
  namespace: production
spec:
  project: deployment

  source:
    repoURL: https://github.com/Naomi-org/argocd-test101.git
    targetRevision: main
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
